score = int(input('Please enter test score:'))
if score>99:
    print('YOU DO NOT SUCK TRY BETTER NEXT TIME')
else:
    print('CONGRATS NOW GO JUMP OFF A CLIFF BECAUSE WE ALL KNOW YOU ARE THE ATTENTION-LACKING CHILD WHO IS NOT THEIR STRICT PARENTS FAVOURITE CHILD. DO BETTER NEXT TIME.')